### ISSUE TITLE
Structural identifiability analysis performed for different parameters in Goodwin and GoodwinPoly

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#12]
Is this intentional? I think it would be nicer to have this consistent to facilitate the comparability of the results.

**Comment by genssi-developer** [comment]
The Goodwin model has 8 parameters, but only 7 were being used for analysis. This was probably done to match the original test, so that the runtimes would be comparable. However, all 8 parameters can be analyzed with 5 derivatives, so this was changed. Now, all 8 parameters are identified as locally identifiable, and Goodwin (GoodwinPoly) runs in 2.1 (2.3) seconds.
