### ISSUE TITLE
GenSSI - not working

### ISSUE THREAD

**Issue by josselfer** [genssi-developer/GenSSI#18]
Hi,

I had successfully used GenSSI one month ago under Matlab R2017b but today I tried again and it does not work anymore. It gets stuck after typing "yes" (even with one of the provided examples). Any thought about?

**Comment by JanHasenauer** [comment]
Dear josselfer,
thanks for you comment. We did not update GenSSI during the last month, according, it should not be a release issue. If there is the possibility that you modified a routine, I would suggest to download the most recent version.
If this does not help, it would be interesting to know if there is an error message or what the screen output is.
Thanks in advance,
Jan

**Comment by thomassligon** [comment]
Dear Josselfer,
can you tell us if you are still using MATLAB R2017b, or did you do this test with R2018a? In addition, what is the error message from MATLAB when it fails?
Thanks,
Tom

**Comment by josselfer** [comment]
Hi Jan and Thomas. 
After searching for possible problems I realized that the problem popped up because a recent windows update that messed the installations of both R2017b and R2018a. Now , after using an update that MathWorks provided for this issue the syms command ran and everything came back to normality. I provide the wire since it may be helpful for another user:

https://www.mathworks.com/matlabcentral/answers/392947-matlab-memory-leak-when-creating-symbolic-variables 

https://www.mathworks.com/support/bugreports/1755918

Thanks for your support,

José.

**Comment by thomassligon** [comment]
I had the same problem. Here is what I got from MathWorks support:

This bug is known and already solved for both releases. The solution is to update both releases, however the required update for R2017b is not available yet but will be approximately in the end of May.

R2018a:
Please update your MATLAB R2018a version to Update 2. The installation link can be found here:
https://www.mathworks.com/downloads/web_downloads/download_update?release=R2018a&s_tid=ebrg_R2018a_1_1755918?

R2017b:
The required update is Update 7. As this update is not available yet, you can subscribe to the bug report to get informed about the latest news: https://www.mathworks.com/support/bugreports/search_results?utf8=%E2%9C%93&search_executed=1&keyword=1755918&release_filter=Exists+in&release=280&selected_products=&commit=Search

When the new update is released you can find the download link here:
https://www.mathworks.com/downloads/web_downloads/show_updates?release=R2017b
