### ISSUE TITLE
run files for M1 and M2 examples missing

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#4]
We should add them to simplify the reuse of the models for other users.

**Comment by thomassligon** [comment]
Yes, I’ll do that.
I recently put these models in because they are used in the refman, for multi-experiment and transformation. I have model definitions for all 6 mRNA models in Laura’s thesis, including 4 variants for each one, but we decided not to include them all.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by genssi-developer** [comment]
Run scripts now exist for all models, including examples of using conversion routines.
