### ISSUE TITLE
Illustration of construction of multi-experiment model

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#5]
Transfection3 provides a multi-experiment model. There is however no example which illustrates how a multi-experiment model ist constructed. I think it would be good to modify Transfection3:
- add file describing the experimental conditions and
- modify runTransfection3 to construct the multi-experiment model.

**Comment by thomassligon** [comment]
Hello Jan,

“There is however no example which illustrates how a multi-experiment model ist constructed”

Yes, there is!!! This is documented in the refman, and is part of model M1_1_ME4, which also contains a run script with all of the steps required (and documented in the refman).

Since this still seems to be confusing, even though the example is on file and includes a run script, my suggestion would be to rename all of the M1_... and M2_... examples and merge them with the Transfection… examples.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by JanHasenauer** [comment]
Dear Tom,

thanks for pointing out the file. I had a look at all, but apparently missed it. I think that this shows that we need a better naming scheme and a better in code documentation in the run file. I can do that.
Merging the examples is probably a good idea.

Greetings, Jan
